// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementRepoPattern.Data;

#nullable disable

namespace StudentManagementRepoPattern.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementRepoPattern.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = ".NET Full Stack Development",
                            DepartmentId = 1,
                            Duration = "6 Months"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Angular Development",
                            DepartmentId = 1,
                            Duration = "4 Months"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "Cloud Computing",
                            DepartmentId = 2,
                            Duration = "6 Months"
                        },
                        new
                        {
                            CourseId = 4,
                            CourseName = "Cyber Security",
                            DepartmentId = 2,
                            Duration = "5 Months"
                        },
                        new
                        {
                            CourseId = 5,
                            CourseName = "Financial Management",
                            DepartmentId = 3,
                            Duration = "3 Months"
                        });
                });

            modelBuilder.Entity("StudentManagementRepoPattern.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Computer Science",
                            Location = "Building A"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Information Technology",
                            Location = "Building B"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Business Administration",
                            Location = "Building C"
                        });
                });

            modelBuilder.Entity("StudentManagementRepoPattern.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            AdmissionDate = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 22,
                            CourseId = 1,
                            DepartmentId = 1,
                            Email = "ravi@gmail.com",
                            Gender = "Male",
                            Name = "Ravi Kumar"
                        },
                        new
                        {
                            StudentId = 2,
                            AdmissionDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 23,
                            CourseId = 3,
                            DepartmentId = 2,
                            Email = "anjali@gmail.com",
                            Gender = "Female",
                            Name = "Anjali Sharma"
                        },
                        new
                        {
                            StudentId = 3,
                            AdmissionDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 24,
                            CourseId = 2,
                            DepartmentId = 1,
                            Email = "suresh@gmail.com",
                            Gender = "Male",
                            Name = "Suresh Reddy"
                        },
                        new
                        {
                            StudentId = 4,
                            AdmissionDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 21,
                            CourseId = 5,
                            DepartmentId = 3,
                            Email = "priya@gmail.com",
                            Gender = "Female",
                            Name = "Priya Nair"
                        });
                });

            modelBuilder.Entity("StudentManagementRepoPattern.Models.Course", b =>
                {
                    b.HasOne("StudentManagementRepoPattern.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentManagementRepoPattern.Models.Student", b =>
                {
                    b.HasOne("StudentManagementRepoPattern.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagementRepoPattern.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentManagementRepoPattern.Models.Course", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagementRepoPattern.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
