

ALTER TABLE ZIPCODE_INFO
ADD CONSTRAINT ZIP_PK
PRIMARY KEY (ZIP_CODE);

ALTER TABLE ZIPCODE_INFO
MODIFY CITY CONSTRAINT ZIP_CITY_NN NOT NULL;

ALTER TABLE ZIPCODE_INFO
MODIFY STATE CONSTRAINT ZIP_STATE_NN NOT NULL;


ALTER TABLE INSTRUCTOR_INFO
ADD CONSTRAINT INSTRUCTOR_ID_PK
PRIMARY KEY (INSTRUCTOR_ID);

ALTER TABLE INSTRUCTOR_INFO
MODIFY INSTRUCTOR_FIRST_NAME
CONSTRAINT INSTRUCTOR_FN_NN NOT NULL;

ALTER TABLE INSTRUCTOR_INFO
MODIFY INSTRUCTOR_LAST_NAME
CONSTRAINT INSTRUCTOR_LN_NN NOT NULL;

ALTER TABLE INSTRUCTOR_INFO
ADD CONSTRAINT ZIP_INSTRUCTOR_FK
FOREIGN KEY (ZIP_CODE)
REFERENCES ZIPCODE_INFO (ZIP_CODE);




ALTER TABLE COURSE_INFO
ADD CONSTRAINT COURSE_NO_PK
PRIMARY KEY (COURSE_NO);

ALTER TABLE COURSE_INFO
MODIFY COURSE_NAME
CONSTRAINT COURSE_NAME_NN NOT NULL;

ALTER TABLE COURSE_INFO
MODIFY COST
CONSTRAINT COST_NN NOT NULL;


ALTER TABLE STUDENT_INFO
ADD CONSTRAINT STUDENT_ID_PK
PRIMARY KEY (STUDENT_ID);

ALTER TABLE STUDENT_INFO
MODIFY STUDENT_FIRST_NAME
CONSTRAINT STUDENT_FN_NN NOT NULL;

ALTER TABLE STUDENT_INFO
MODIFY STUDENT_LAST_NAME
CONSTRAINT STUDENT_LN_NN NOT NULL;

ALTER TABLE STUDENT_INFO
ADD CONSTRAINT ZIP_STUDENT_FK
FOREIGN KEY (ZIP_CODE)
REFERENCES ZIPCODE_INFO (ZIP_CODE);


ALTER TABLE SECTION_INFO
ADD CONSTRAINT SECTION_ID_PK
PRIMARY KEY (SECTION_ID);


ALTER TABLE SECTION_INFO
MODIFY SECTION_NO
CONSTRAINT SECTION_NO_NN NOT NULL;

ALTER TABLE SECTION_INFO
ADD CONSTRAINT COURSE_SECTION_FK
FOREIGN KEY (COURSE_NO)
REFERENCES COURSE_INFO (COURSE_NO);

ALTER TABLE SECTION_INFO
ADD CONSTRAINT INSTRUCTOR_SECTION_FK
FOREIGN KEY (INSTRUCTOR_ID)
REFERENCES INSTRUCTOR_INFO (INSTRUCTOR_ID);




ALTER TABLE ENROLLMENT_INFO
ADD CONSTRAINT ENROLLMENT_STUD_SECT_PK
PRIMARY KEY (STUDENT_ID, SECTION_ID);

ALTER TABLE ENROLLMENT_INFO
ADD CONSTRAINT ENROLLMENT_STUDENT_ID_FK
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT_INFO (STUDENT_ID);

ALTER TABLE ENROLLMENT_INFO
ADD CONSTRAINT ENROLLMENT_SECTION_ID_FK
FOREIGN KEY (SECTION_ID)
REFERENCES SECTION_INFO (SECTION_ID);



ALTER TABLE GRADE_INFO
ADD CONSTRAINT GRADE_STUD_SECT_TYPE_CODE_PK
PRIMARY KEY (STUDENT_ID, SECTION_ID, GRADE_TYPE_CODE, GRADE_CODE_OCCURANCE);

ALTER TABLE GRADE_INFO
ADD CONSTRAINT GRADE_STUDENT_ID_FK
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT_INFO (STUDENT_ID);

ALTER TABLE GRADE_INFO
ADD CONSTRAINT GRADE_SECTION_ID_FK
FOREIGN KEY (SECTION_ID)
REFERENCES SECTION_INFO (SECTION_ID);

ALTER TABLE GRADE_INFO
ADD CONSTRAINT CHK_GRADE_TYPE_CODE
CHECK (GRADE_TYPE_CODE IN ('FI','HM','MT','PA','PJ','QZ'));

ALTER TABLE GRADE_INFO
MODIFY NUMERIC_GRADE
DEFAULT 0
CONSTRAINT NUMERIC_GRADE_NN NOT NULL;
